version: '3.8'

services:
  frontend-service:
    build: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true

  backend-service:
    build: ./backend
    ports:
      - 9035:80
    environment:
      - IS_SERVER=true
    # Uncomment the following lines if you want live code reloads during development
    volumes:
       - ./backend:/app
